services:
  authentification:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run start"
    ports:
      -3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      #Database
      - DB_HOST=192.168.20.233
      - DB_PORT=3306
      - DB_NAME=gssprod
      - DB_USER=aglic
      - DB_PASSWORD=Aglic2020
      #Secretkey
      - SECRET_KEY = 5468576D597133743677397A24432646294A404E635266556A586E3272347537